
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# 1. Tracing Sampling Rate
# 1.0 = 100% of requests are traced (ideal for development/testing)
management.tracing.sampling.probability=1.0
logging.include-application-name=true

# 2. Zipkin Server Endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# 3. Log pattern to show Service Name, Trace ID, and Span ID in console
logging.pattern.level=%5p [${spring.application.name:},%X{traceId},%X{spanId}]
