
spring.datasource.url=jdbc:mysql://localhost:3306/department_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 1. Tracing Sampling Rate
# 1.0 = 100% of requests are traced (ideal for development/testing)
management.tracing.sampling.probability=1.0
logging.include-application-name=true

# 2. Zipkin Server Endpoint
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# 3. Log pattern to show Service Name, Trace ID, and Span ID in console
logging.pattern.level=%5p [${spring.application.name:},%X{traceId},%X{spanId}]
